### ISSUE TITLE
Unknown Error Log

### ISSUE THREAD

**Issue by PrimeStrat** [EndstoneMC/endstone#101]
I have been unable to reproduce the bug reliably but it has happened on users joins- more specifically we run a cinematic camera command along with a teleport on join via Script API.

Error Log:

[2024-12-05 20:18:37.125 ERROR] [Server] Trying to access location (27, 63, 14) which is outside of the world boundaries.
[2024-12-05 20:18:37.125 ERROR] [Server] Stack trace (most recent call first):
#0  0x00007ffe1758dc47 in endstone::detail::make_error(std::basic_string_view<char, std::char_traits<char> >) at D:\a\endstone\endstone\src\endstone_core\util\error.cpp:23
#1  0x00007ffe1756a2c4 in endstone::detail::make_error<int const &, int const &, int const &>(fmt::v10::basic_format_string<char, int const &, int const &, int const &>, int&, int&, int&) at D:\a\endstone\endstone\include\endstone\detail\util\error.h:28
#2  0x00007ffe1756b41d in endstone::detail::EndstoneBlock::checkState() at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:167
#3  0x00007ffe1756b033 in endstone::detail::EndstoneBlock::at(BlockPos) at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:158
#4  0x00007ffe174a1475 in GameMode::useItemOn(GameMode*, ItemStack&, BlockPos&, unsigned int, unsigned int, Vec3&) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\world\gamemode\game_mode.cpp:58
#5  0x00007ff6cabf2d6e in  ??
#6  0x00007ff6cabd049e in  ??
#7  0x00007ff6ca645515 in  ??
#8  0x00007ff6ca5e6d7a in  ??
#9  0x00007ff6cabe31d1 in  ??
#10 0x00007ff6cabe876b in  ??
#11 0x00007ff6cabe8b27 in  ??
#12 0x00007ff6c94d4dd6 in  ??
#13 0x00007ff6c92007b3 in  ??
#14 0x00007ff6c9189d95 in  ??
#15 0x00007ff6c91824e3 in  ??
#16 0x00007ff6c917759a in  ??
#17 0x00007ff6c9193f18 in  ??
#18 0x00007ff6ca663ab7 in  ??
#19 0x00007ff6c975f07b in  ??
#20 0x00007ff6c9752c3f in  ??
#21 0x00007ff6c96a8a7d in  ??
#22 0x00007ffe6ae59332 in _recalloc
#23 0x00007ffe6c58259c in BaseThreadInitThunk
#24 0x00007ffe6d56af37 in RtlUserThreadStart
[2024-12-05 20:18:37.138 ERROR] [Server] Trying to access location (27, 63, 14) which is outside of the world boundaries.
[2024-12-05 20:18:37.139 ERROR] [Server] Stack trace (most recent call first):
#0  0x00007ffe1758dc47 in endstone::detail::make_error(std::basic_string_view<char, std::char_traits<char> >) at D:\a\endstone\endstone\src\endstone_core\util\error.cpp:23
#1  0x00007ffe1756a2c4 in endstone::detail::make_error<int const &, int const &, int const &>(fmt::v10::basic_format_string<char, int const &, int const &, int const &>, int&, int&, int&) at D:\a\endstone\endstone\include\endstone\detail\util\error.h:28
#2  0x00007ffe1756b41d in endstone::detail::EndstoneBlock::checkState() at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:167
#3  0x00007ffe1756b033 in endstone::detail::EndstoneBlock::at(BlockPos) at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:158
#4  0x00007ffe174a1475 in GameMode::useItemOn(GameMode*, ItemStack&, BlockPos&, unsigned int, unsigned int, Vec3&) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\world\gamemode\game_mode.cpp:58
#5  0x00007ff6cabf2d6e in  ??
#6  0x00007ff6cabd049e in  ??
#7  0x00007ff6ca645515 in  ??
#8  0x00007ff6ca5e6d7a in  ??
#9  0x00007ff6cabe31d1 in  ??
#10 0x00007ff6cabe876b in  ??
#11 0x00007ff6cabe8b27 in  ??
#12 0x00007ff6c94d4dd6 in  ??
#13 0x00007ff6c92007b3 in  ??
#14 0x00007ff6c9189d95 in  ??
#15 0x00007ff6c91824e3 in  ??
#16 0x00007ff6c917759a in  ??
#17 0x00007ff6c9193f18 in  ??
#18 0x00007ff6ca663ab7 in  ??
#19 0x00007ff6c975f07b in  ??
#20 0x00007ff6c9752c3f in  ??
#21 0x00007ff6c96a8a7d in  ??
#22 0x00007ffe6ae59332 in _recalloc
#23 0x00007ffe6c58259c in BaseThreadInitThunk
#24 0x00007ffe6d56af37 in RtlUserThreadStart
[2024-12-05 20:18:37.140 ERROR] [Server] Trying to access location (27, 63, 14) which is outside of the world boundaries.
[2024-12-05 20:18:37.141 ERROR] [Server] Stack trace (most recent call first):
#0  0x00007ffe1758dc47 in endstone::detail::make_error(std::basic_string_view<char, std::char_traits<char> >) at D:\a\endstone\endstone\src\endstone_core\util\error.cpp:23
#1  0x00007ffe1756a2c4 in endstone::detail::make_error<int const &, int const &, int const &>(fmt::v10::basic_format_string<char, int const &, int const &, int const &>, int&, int&, int&) at D:\a\endstone\endstone\include\endstone\detail\util\error.h:28
#2  0x00007ffe1756b41d in endstone::detail::EndstoneBlock::checkState() at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:167
#3  0x00007ffe1756b033 in endstone::detail::EndstoneBlock::at(BlockPos) at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:158
#4  0x00007ffe174a1475 in GameMode::useItemOn(GameMode*, ItemStack&, BlockPos&, unsigned int, unsigned int, Vec3&) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\world\gamemode\game_mode.cpp:58
#5  0x00007ff6cabf2d6e in  ??
#6  0x00007ff6cabd049e in  ??
#7  0x00007ff6ca645515 in  ??
#8  0x00007ff6ca5e6d7a in  ??
#9  0x00007ff6cabe31d1 in  ??
#10 0x00007ff6cabe876b in  ??
#11 0x00007ff6cabe8b27 in  ??
#12 0x00007ff6c94d4dd6 in  ??
#13 0x00007ff6c92007b3 in  ??
#14 0x00007ff6c9189d95 in  ??
#15 0x00007ff6c91824e3 in  ??
#16 0x00007ff6c917759a in  ??
#17 0x00007ff6c9193f18 in  ??
#18 0x00007ff6ca663ab7 in  ??
#19 0x00007ff6c975f07b in  ??
#20 0x00007ff6c9752c3f in  ??
#21 0x00007ff6c96a8a7d in  ??
#22 0x00007ffe6ae59332 in _recalloc
#23 0x00007ffe6c58259c in BaseThreadInitThunk
#24 0x00007ffe6d56af37 in RtlUserThreadStart
[2024-12-05 20:18:37.142 ERROR] [Server] Trying to access location (27, 63, 14) which is outside of the world boundaries.
[2024-12-05 20:18:37.142 ERROR] [Server] Stack trace (most recent call first):
#0  0x00007ffe1758dc47 in endstone::detail::make_error(std::basic_string_view<char, std::char_traits<char> >) at D:\a\endstone\endstone\src\endstone_core\util\error.cpp:23
#1  0x00007ffe1756a2c4 in endstone::detail::make_error<int const &, int const &, int const &>(fmt::v10::basic_format_string<char, int const &, int const &, int const &>, int&, int&, int&) at D:\a\endstone\endstone\include\endstone\detail\util\error.h:28
#2  0x00007ffe1756b41d in endstone::detail::EndstoneBlock::checkState() at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:167
#3  0x00007ffe1756b033 in endstone::detail::EndstoneBlock::at(BlockPos) at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:158
#4  0x00007ffe174a1475 in GameMode::useItemOn(GameMode*, ItemStack&, BlockPos&, unsigned int, unsigned int, Vec3&) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\world\gamemode\game_mode.cpp:58
#5  0x00007ff6cabf2d6e in  ??
#6  0x00007ff6cabd049e in  ??
#7  0x00007ff6ca645515 in  ??
#8  0x00007ff6ca5e6d7a in  ??
#9  0x00007ff6cabe31d1 in  ??
#10 0x00007ff6cabe876b in  ??
#11 0x00007ff6cabe8b27 in  ??
#12 0x00007ff6c94d4dd6 in  ??
#13 0x00007ff6c92007b3 in  ??
#14 0x00007ff6c9189d95 in  ??
#15 0x00007ff6c91824e3 in  ??
#16 0x00007ff6c917759a in  ??
#17 0x00007ff6c9193f18 in  ??
#18 0x00007ff6ca663ab7 in  ??
#19 0x00007ff6c975f07b in  ??
#20 0x00007ff6c9752c3f in  ??
#21 0x00007ff6c96a8a7d in  ??
#22 0x00007ffe6ae59332 in _recalloc
#23 0x00007ffe6c58259c in BaseThreadInitThunk
#24 0x00007ffe6d56af37 in RtlUserThreadStart
[2024-12-05 20:18:37.144 ERROR] [Server] Trying to access location (27, 63, 14) which is outside of the world boundaries.
[2024-12-05 20:18:37.144 ERROR] [Server] Stack trace (most recent call first):
#0  0x00007ffe1758dc47 in endstone::detail::make_error(std::basic_string_view<char, std::char_traits<char> >) at D:\a\endstone\endstone\src\endstone_core\util\error.cpp:23
#1  0x00007ffe1756a2c4 in endstone::detail::make_error<int const &, int const &, int const &>(fmt::v10::basic_format_string<char, int const &, int const &, int const &>, int&, int&, int&) at D:\a\endstone\endstone\include\endstone\detail\util\error.h:28
#2  0x00007ffe1756b41d in endstone::detail::EndstoneBlock::checkState() at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:167
#3  0x00007ffe1756b033 in endstone::detail::EndstoneBlock::at(BlockPos) at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:158
#4  0x00007ffe174a1475 in GameMode::useItemOn(GameMode*, ItemStack&, BlockPos&, unsigned int, unsigned int, Vec3&) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\world\gamemode\game_mode.cpp:58
#5  0x00007ff6cabf2d6e in  ??
#6  0x00007ff6cabd049e in  ??
#7  0x00007ff6ca645515 in  ??
#8  0x00007ff6ca5e6d7a in  ??
#9  0x00007ff6cabe31d1 in  ??
#10 0x00007ff6cabe876b in  ??
#11 0x00007ff6cabe8b27 in  ??
#12 0x00007ff6c94d4dd6 in  ??
#13 0x00007ff6c92007b3 in  ??
#14 0x00007ff6c9189d95 in  ??
#15 0x00007ff6c91824e3 in  ??
#16 0x00007ff6c917759a in  ??
#17 0x00007ff6c9193f18 in  ??
#18 0x00007ff6ca663ab7 in  ??
#19 0x00007ff6c975f07b in  ??
#20 0x00007ff6c9752c3f in  ??
#21 0x00007ff6c96a8a7d in  ??
#22 0x00007ffe6ae59332 in _recalloc
#23 0x00007ffe6c58259c in BaseThreadInitThunk
#24 0x00007ffe6d56af37 in RtlUserThreadStart
[2024-12-05 20:18:37.146 ERROR] [Server] Trying to access location (27, 63, 14) which is outside of the world boundaries.
[2024-12-05 20:18:37.146 ERROR] [Server] Stack trace (most recent call first):
#0  0x00007ffe1758dc47 in endstone::detail::make_error(std::basic_string_view<char, std::char_traits<char> >) at D:\a\endstone\endstone\src\endstone_core\util\error.cpp:23
#1  0x00007ffe1756a2c4 in endstone::detail::make_error<int const &, int const &, int const &>(fmt::v10::basic_format_string<char, int const &, int const &, int const &>, int&, int&, int&) at D:\a\endstone\endstone\include\endstone\detail\util\error.h:28
#2  0x00007ffe1756b41d in endstone::detail::EndstoneBlock::checkState() at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:167
#3  0x00007ffe1756b033 in endstone::detail::EndstoneBlock::at(BlockPos) at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:158
#4  0x00007ffe174a1475 in GameMode::useItemOn(GameMode*, ItemStack&, BlockPos&, unsigned int, unsigned int, Vec3&) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\world\gamemode\game_mode.cpp:58
#5  0x00007ff6cabf2d6e in  ??
#6  0x00007ff6cabd049e in  ??
#7  0x00007ff6ca645515 in  ??
#8  0x00007ff6ca5e6d7a in  ??
#9  0x00007ff6cabe31d1 in  ??
#10 0x00007ff6cabe876b in  ??
#11 0x00007ff6cabe8b27 in  ??
#12 0x00007ff6c94d4dd6 in  ??
#13 0x00007ff6c92007b3 in  ??
#14 0x00007ff6c9189d95 in  ??
#15 0x00007ff6c91824e3 in  ??
#16 0x00007ff6c917759a in  ??
#17 0x00007ff6c9193f18 in  ??
#18 0x00007ff6ca663ab7 in  ??
#19 0x00007ff6c975f07b in  ??
#20 0x00007ff6c9752c3f in  ??
#21 0x00007ff6c96a8a7d in  ??
#22 0x00007ffe6ae59332 in _recalloc
#23 0x00007ffe6c58259c in BaseThreadInitThunk
#24 0x00007ffe6d56af37 in RtlUserThreadStart
[2024-12-05 20:18:37.147 ERROR] [Server] Trying to access location (27, 63, 14) which is outside of the world boundaries.
[2024-12-05 20:18:37.148 ERROR] [Server] Stack trace (most recent call first):
#0  0x00007ffe1758dc47 in endstone::detail::make_error(std::basic_string_view<char, std::char_traits<char> >) at D:\a\endstone\endstone\src\endstone_core\util\error.cpp:23
#1  0x00007ffe1756a2c4 in endstone::detail::make_error<int const &, int const &, int const &>(fmt::v10::basic_format_string<char, int const &, int const &, int const &>, int&, int&, int&) at D:\a\endstone\endstone\include\endstone\detail\util\error.h:28
#2  0x00007ffe1756b41d in endstone::detail::EndstoneBlock::checkState() at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:167
#3  0x00007ffe1756b033 in endstone::detail::EndstoneBlock::at(BlockPos) at D:\a\endstone\endstone\src\endstone_core\block\block.cpp:158
#4  0x00007ffe174a1475 in GameMode::useItemOn(GameMode*, ItemStack&, BlockPos&, unsigned int, unsigned int, Vec3&) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\world\gamemode\game_mode.cpp:58
#5  0x00007ff6cabf2d6e in  ??
#6  0x00007ff6cabd049e in  ??
#7  0x00007ff6ca645515 in  ??
#8  0x00007ff6ca5e6d7a in  ??
#9  0x00007ff6cabe31d1 in  ??
#10 0x00007ff6cabe876b in  ??
#11 0x00007ff6cabe8b27 in  ??
#12 0x00007ff6c94d4dd6 in  ??
#13 0x00007ff6c92007b3 in  ??
#14 0x00007ff6c9189d95 in  ??
#15 0x00007ff6c91824e3 in  ??
#16 0x00007ff6c917759a in  ??
#17 0x00007ff6c9193f18 in  ??
#18 0x00007ff6ca663ab7 in  ??
#19 0x00007ff6c975f07b in  ??
#20 0x00007ff6c9752c3f in  ??
#21 0x00007ff6c96a8a7d in  ??
#22 0x00007ffe6ae59332 in _recalloc
#23 0x00007ffe6c58259c in BaseThreadInitThunk
#24 0x00007ffe6d56af37 in RtlUserThreadStart

**Comment by wu-vincent** [comment]
Which version are you using? This should've been fixed since 0.5.6.dev70.
