### ISSUE TITLE
[feature] Change Permission level for /allowlist /whitelist etc.

### ISSUE THREAD

**Issue by BuslnwTH** [EndstoneMC/endstone#105]
**Is your feature request related to a problem? Please describe.**
I'm having a lot of trouble using some commands that are only available on the console.

**Describe the solution you'd like**
Reduce permissions level for some built-in commands in bds. To be useful on the player side

**Comment by wu-vincent** [comment]
Thank you for your suggestion! After reviewing this request, I checked the behavior in the Java Edition of Minecraft and found that the same command is also restricted to the console. Regardless of the original design's intention, I believe it is more appropriate to keep this as is to maintain consistency and avoid potential security issues.

However, if you have alternative suggestions, please feel free to share more details.
