### ISSUE TITLE
[bug]set the allow_flight attr into False will cause the player lost all the abilities!!!

### ISSUE THREAD

**Issue by ye111566** [EndstoneMC/endstone#106]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - Endstone Version: [e.g. v0.4.0]

**Additional context**

**Comment by ye111566** [comment]
I use the Player().allow_flight=False and i can't do anything such as mine!

**Comment by wu-vincent** [comment]
Thanks for reporting the issue. Can you show me your codes that set `allow_flight` to `False`?

**Comment by ye111566** [comment]
> Thanks for reporting the issue. Can you show me your codes that set `allow_flight` to `False`?

self.server.get_player(playername:str).allow_flight=True

**Comment by wu-vincent** [comment]
Where did you attempt to set that to `True`? I assume you set it in one of the event handlers?

**Comment by ye111566** [comment]
> 你尝试将其设置在哪里？我假设您在其中一个事件处理程序中设置它？`True`

in the event handler"on player join"

**Comment by wu-vincent** [comment]
This has been known as a "client-side" bug for a while. If you try to set it in the PlayerJoinEvent handler, the client might not be able to break or place blocks. For now, the workaround is to either add a command to set it or start a delayed task in the event handler to set it. Basically, just avoid setting it directly in PlayerJoinEvent.
