### ISSUE TITLE
[bug] Player inventory clear() method does not update the Inventory on client side instantly

### ISSUE THREAD

**Issue by AcquaticLegend** [EndstoneMC/endstone#108]
**Describe the bug**
When the `clear()` method is used to clear a player's inventory, the inventory doesn't update on the player's screen until they interact with it, like dropping or adding an item.

**To Reproduce**
`if isinstance(sender, Player):
sender.inventory.clear()
sender.send_message("Inventory cleared!")`

**Expected behavior**
Clear the inventory and updates it client side.

**Screenshots**
![image](https://github.com/user-attachments/assets/c4816ce4-a108-4713-ac41-74274ffcb3bc)
^^ Inventory before running the command 
![image](https://github.com/user-attachments/assets/1dcfabf8-a373-4ca8-963b-d7c6eabb7c4d)
^^ Inventory after running the command
![image](https://github.com/user-attachments/assets/aba32f8b-6b26-454f-8f10-71770c00b70d)
^^ Inventory after trying to drop an item pressing Q.
**Details (please complete the following information):**
 - OS: Windows
 - Endstone Version: 0.5.6

**Additional context**
At the moment I have found a way to make it function as intended by adding: `sender.inventory.set_item(0, ItemStack("minecraft:air", 1)))`
 after `clear()`
Sorry about the messy code formatting - I couldn't figure out how to get the indentation right.

**Comment by wu-vincent** [comment]
Thank you for reporting this! I can confirm this is indeed a bug and has just been fixed in the recent commits. The fixes will come with the next release shortly.
