### ISSUE TITLE
Better plugins... [feature]

### ISSUE THREAD

**Issue by cheditx** [EndstoneMC/endstone#20]
As a python developer, i don't really like the plugin creation on this software, whats the sense of making pyproject.toml files, useless subdirectory etc...

Maybe something like this would be great!

![image](https://github.com/EndstoneMC/endstone/assets/66524955/0fdac09d-3d24-4707-a92f-261d35bd10fb)

**Comment by wu-vincent** [comment]
As a Python developer, you should probably know that creating plugins using `pyproject.toml` and `entrypoints` is the [recommended method]. That's the standard way that many other projects like flask, pytest, flake8 adopted. You will see all projects using this method here: https://github.com/search?q=project.entry-points.&type=code

I understand that it may seem a bit verbose, but it's just a one-time setup. Once you have it set up, you're good to go.

[recommended method]: https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/
