### ISSUE TITLE
[bug] Duplicate furnace aux recipes

### ISSUE THREAD

**Issue by wu-vincent** [EndstoneMC/endstone#25]
**Describe the bug**
The furnace aux recipes are duplicated.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - Endstone Version: [e.g. v0.4.0]

**Additional context**

**Comment by KoshakMineDEV** [comment]
any progress with that?

**Comment by smartcmd** [comment]
Remove it manually

**Comment by wu-vincent** [comment]
Okay. These are not really duplicates recipes. In fact, the outputs have different nbt data which was not displayed (and probably not needed i assume?).

Anyway, since this only happens to a few recipes, I suggest doing some filtering but not at the endstone side as it will not help reducing the size much.

I am going to close the issue as won't fix for now.
