### ISSUE TITLE
[bug] In "permissions" OP and OPERATOR have the same level of permission.

### ISSUE THREAD

**Issue by MengHanLOVE1027** [EndstoneMC/endstone#27]
**Describe the bug**
The values "OP" and "OPERATOR" in "permissions" refer to the same type of permission.
This issue is machine-translated, please excuse any discrepancies.

**To Reproduce**

1. Write content in the plugin:
   (This is the code)
```python
commands = {
        "backuptrue": {
            "description": "test True",
            "usages": ["/backuptrue"],
            "aliases": ["EasyBackuper"],
            "permissions": ["python_example.command.true"]
        },
        "backupfalse": {
            "description": "test False",
            "usages": ["/backupfalse"],
            "aliases": ["EasyBackuper"],
            "permissions": ["python_example.command.false"]
        },
        "backupop": {
            "description": "test is op",
            "usages": ["/backupop"],
            "aliases": ["EasyBackuper"],
            "permissions": ["python_example.command.op"]
        },
        "backupunop": {
            "description": "test not op",
            "usages": ["/backupunop"],
            "aliases": ["EasyBackuper"],
            "permissions": ["python_example.command.unop"]
        },
        "backupconsole": {
            "description": "test is console",
            "usages": ["/backupconsole"],
            "aliases": ["EasyBackuper"],
            "permissions": ["python_example.command.operator"]
        },
        "backupunconsole": {
            "description": "test not console",
            "usages": ["/backupunconsole"],
            "aliases": ["EasyBackuper"],
            "permissions": ["python_example.command.unoperator"]
        }
    }
    permissions = {
        "python_example.command": {
            "description": "Allow users to use all commands provided by this plugin.",
            "default": True,
            "children": {
                "python_example.command.python": True,
            },
        },
        "python_example.command.true": {
            "description": "Allow users to use the /python command.",
            "default": True,
        },
        "python_example.command.false": {
            "description": "Allow users to use the /python command.",
            "default": False,
        },
        "python_example.command.op": {
            "description": "Allow users to use the /kickme command.",
            "default": "op",
        },
        "python_example.command.unop": {
            "description": "Allow users to use the /kickme command.",
            "default": "not_op",
        },
        "python_example.command.operator": {
            "description": "Allow users to use the /kickme command.",
            "default": "operator",
        },
        "python_example.command.unoperator": {
            "description": "Allow users to use the /kickme command.",
            "default": "not_operator",
        }
    }
```

2. Build the plugin and place it in the 'plugins' folder.
3. Start the server.
4. Open Minecraft.
5. Go to the server and join it.
6. Type `/backup` to test (without obtaining OP status).
7. See the result (see screenshot below).
![屏幕截图 2024-07-29 093340](https://github.com/user-attachments/assets/58759e03-bf49-4efd-b389-5819af5e332a)

8. Type `/backup` again to test (after obtaining OP status).
9. See the result (see screenshot below).
![屏幕截图 2024-07-29 093353](https://github.com/user-attachments/assets/2d513581-84d2-4480-9580-2a4c32d8f2b8)
10. Observe that it appears OP and OPERATOR have equivalent permissions.

**Expected behavior**
I think OP and OPERATOR are two different permissions. For example, OP can be executed by OP players as well as by the console, but OPERATOR can only be executed by the console.

**Screenshots**
See above.

**Details (please complete the following information):**
 - OS: Windows 11 x64
 - Endstone Version: v0.4.10

**Additional context**
None.

**Comment by MengHanLOVE1027** [comment]
![image](https://github.com/user-attachments/assets/a2112ba3-58c7-4d37-974d-6bd716e3ddb7)
Their real values are the same.
🤣→→😐→→🤐

**Comment by wu-vincent** [comment]
This is expected behavior. op is an alias of operator. :P

**Comment by MengHanLOVE1027** [comment]
I know it now. hmmm, may you add another enum member for the console? QwQ
This is beneficial for distinguishing whether the command source is OP or Console. AwA

~~Although there is an impact from pdb, I still support your project.~~OwO
