### ISSUE TITLE
[bug] Creating a form without a on submit callback crashes the server

### ISSUE THREAD

**Issue by zSALLAZAR** [EndstoneMC/endstone#32]
**Describe the bug**
Creating a form without a on submit callback crashes the server

**To Reproduce**
1. Create a ActionForm
2. Add buttons
3. Click on a button

**Expected behavior**
The form should just close

**Screenshots**

**Details (please complete the following information):**
 - OS: Windows
 - Endstone Version: v0.5.0

**Additional context**

**Comment by wu-vincent** [comment]
I can't reproduce it locally. Could you attach the screenshots of the crash logs and your code? That will be helpful.

**Comment by wu-vincent** [comment]
Thanks, I am able to reproduce it now. I will look into it.

**Comment by wu-vincent** [comment]
Can confirm this is now fixed in https://github.com/EndstoneMC/endstone/commit/89058cdf750c02f8eb9e71cd976ab452ab47af30. Thanks for reporting this! I will shortly make another release.
