### ISSUE TITLE
[bug]Unable to start the server

### ISSUE THREAD

**Issue by Monarchdos** [EndstoneMC/endstone#35]
**Describe the bug**
Can't start the server using docker and pip.

**To Reproduce**
docker run and endstone commands

**Screenshots**
![2024-08-15_10-41-35](https://github.com/user-attachments/assets/acfbc666-33db-47b7-9601-533114d06f53)
![123](https://github.com/user-attachments/assets/48c625de-d5c0-436b-8722-6fc24f081c0d)

**Comment by wu-vincent** [comment]
This will happen if you have a server installation whose version does not match with your endstone version. An easy fix is to delete the bedrock_server/bedrock_server.exe and bedrock_server/bedrock_server. Then start endstone again to download the correct version.

**Comment by Monarchdos** [comment]
And I'm also getting this error when I use a docker image directly.

**Comment by wu-vincent** [comment]
Can you try to run the docker image without volumn mount and see if it works?

**Comment by Monarchdos** [comment]
I tried it and it works fine, why doesn't volumn mount work?

**Comment by wu-vincent** [comment]
Same reason as i mentioned above. There must be an installation with the wrong version in your mounted folder.

**Comment by Monarchdos** [comment]
But the folder is empty.

**Comment by Monarchdos** [comment]
![image](https://github.com/user-attachments/assets/85208f64-70fc-4110-abe1-23dc72be9c3e)
This is the effect I just reproduced, I created a new folder and executed the command in this folder and it re-downloaded a correct version.

**Comment by wu-vincent** [comment]
Thanks. That's weird. I will look into it later.

**Comment by wu-vincent** [comment]
I am not able to reproduce this. Can you provide more info about your system setup?

**Comment by Monarchdos** [comment]
System:
Linux xxx 4.4.0-19041-Microsoft #4355-Microsoft Thu Apr 12 17:37:00 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
Python:
Python 3.10.12
Pip:
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by Monarchdos** [comment]
Found a new problem, can't start the server even under Windows.
![image](https://github.com/user-attachments/assets/5a798b68-7196-478d-9a62-2c340d7e4c4f)

**Comment by wu-vincent** [comment]
You should've also got a error message box in the meantime. What did it say?

**Comment by Monarchdos** [comment]
Yes, access denied.
![image](https://github.com/user-attachments/assets/04f306a2-a041-4189-842f-1a5e39cbddc5)

**Comment by wu-vincent** [comment]
That's not related to endstone. Please check your file system and make sure it has the right permissions. If it still doesn't work, you can try to use the portable version from the release page.
