### ISSUE TITLE
Support of endstone 

### ISSUE THREAD

**Issue by Mih4n** [EndstoneMC/endstone#36]
**Is your feature request related to a problem? Please describe.**
Yes I cant support endstone by throwing money in to the monitor 

**Describe the solution you'd like**
By me a coffee, Patreon, Busty other

**Describe alternatives you've considered**
No one

**Additional context**
Wanna support endstone but can't. I can give ~10$ monthly but can't. Vincent fix please

**Comment by Mih4n** [comment]
Vincent do not  want my money 😭

**Comment by smartcmd** [comment]
> Vincent do not want my money 😭

You can give me

**Comment by wu-vincent** [comment]
Thank you so much for your support ! I will set it up shortly.

**Comment by xzfg-n15421** [comment]
Added in 903513d

**Comment by wu-vincent** [comment]
Thank you for your patience! Our Ko-fi page is now set up for donations. When you make a one-time donation or subscribe monthly, you'll also receive a special role on Discord as a token of our appreciation. Your support means the world to us. Many thanks again!
