### ISSUE TITLE
[bug] - installing a plugin under linux causes requirement conflicts

### ISSUE THREAD

**Issue by legitbox** [EndstoneMC/endstone#38]
**Describe the bug**
installing a plugin in no matter what enviroment causes the plugin to start throwing venv or --user requirement errors

**To Reproduce**
1. put a plugin in the plugins directory
2. start endstone inside or outside of venv
3. you warnings/errors depending of in what enviroment you ran it in

**Expected behavior**
its supposed to load the plugin in venv mode

**Details (please complete the following information):**
 - OS: Linux Mint 22 x86_64
 - Endstone Version: [0.5.1]

**Comment by wu-vincent** [comment]
It should be fixed by https://github.com/EndstoneMC/endstone/commit/ebc51f989168feb0b000b08ed6e4b27d64e7e3f5 and https://github.com/EndstoneMC/endstone/commit/670a51f799bf6f436f34aa0d47c6d9b56fa6dd63.

Can you download the dev build and see if it works now in a virtual environment?
