### ISSUE TITLE
Publish vanilla bedrock data blobs in a separate repository

### ISSUE THREAD

**Issue by IvanCraft623** [EndstoneMC/endstone#46]
**Describe the solution you'd like**
As tittle. Some other server softwares publish theirs for use by third parties, making it easy to use as a dependency or just a quick glance. e.g.
https://github.com/pmmp/BedrockData
https://github.com/CloudburstMC/Data

**Describe alternatives you've considered**
Make every single users that wants to use data blobs generate them on their own.

**Additional context**
As MagicDroidX mentioned in the BDS Modding Support Meeting, enstone is also oriented to be available to the community, so this would facilitate the use for third parties.

**Comment by smartcmd** [comment]
See https://github.com/AllayMC/BedrockData

**Comment by wu-vincent** [comment]
Thank you for the suggestion, and apologies for the late reply. This will be done, but the current priority is low. For the time being, you can check https://github.com/AllayMC/BedrockData, which contains data from Endstone, although it's not maintained by us.
