### ISSUE TITLE
[bug]I can't Load DLL Plugins

### ISSUE THREAD

**Issue by wellwhz** [EndstoneMC/endstone#47]
**Describe the bug**
Can't Load DLL Plugins. I've copy the example plugin to bedrock_server\plugins\ but it can't work.

**To Reproduce**
1. copy the example plugin
2. run the docker

**Expected behavior**
The DLL plugins can't work, but whl plugins works normally.

**Screenshots**
![image](https://github.com/user-attachments/assets/01bfbe81-da4d-437d-83da-ae00738ad757)

**Details (please complete the following information):**
 - OS: Windows
 - Endstone Version: v0.5.2

**Comment by wu-vincent** [comment]
Since the Docker image runs the Linux build of Endstone, you'll need to place the `.so` file (which is the Linux build of the example plugin) instead of the `.dll` file.
