### ISSUE TITLE
[feature] Add support for Python 3.13

### ISSUE THREAD

**Issue by wu-vincent** [EndstoneMC/endstone#54]
**Is your feature request related to a problem? Please describe.**  
Python 3.13 is currently in the release candidate stage and is scheduled for official release on October 1, 2024 (in approximately 2 weeks). To ensure compatibility with the latest version, we should begin updating our workflows to support Python 3.13.

**Describe the solution you'd like**  
Update the workflow configuration to include Python 3.13 in addition to all previously supported versions.

**Comment by wu-vincent** [comment]
Completed in https://github.com/EndstoneMC/endstone/commit/84c80eaadb7d92cce2f3b8b6d7e94aecba1ed863.

**Comment by smartcmd** [comment]
👀
