### ISSUE TITLE
[feature] make console can auto-complete and highlight

### ISSUE THREAD

**Issue by FTS427** [EndstoneMC/endstone#56]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when typing looooooooooooong and Complex commands, this takes me much time

**Describe the solution you'd like**
Make the console more friendly just be like Nukkit-MOT's console

**Describe alternatives you've considered**
idk😢

**Additional context**
this is an optional feature

**Comment by wu-vincent** [comment]
Thank you for the suggestion! This could be challenging, as it would require taking over the entire console reader implemented by BDS, and the auto-completion would need additional context from the command registry. However, I will still try and see if it's possible. I'll update here once I have more information.

**Comment by FTS427** [comment]
😢
