### ISSUE TITLE
[bug] Server crashes when the world name has non-English characters

### ISSUE THREAD

**Issue by mandong1240** [EndstoneMC/endstone#60]
=== ENDSTONE CRASHED! - PLEASE REPORT THIS AS AN ISSUE ON GITHUB ===
Operation system: Windows
Endstone version: 0.5.4.1
Api version     : 0.5
Description     : Signal received: 22
Stack trace (most recent call first):
#0  0x7fff6d4eb19e     (0x1800cb19e) in endstone::detail::`anonymous namespace'::signal_handler(int) at D:\a\endstone\endstone\src\endstone_runtime\windows\signal_handler.cpp:47
#1  0x7fffe7b9e6d4     (0x18007e6d4) in raise
#2  0x7fffe7b9f6e0     (0x18007f6e0) in abort
#3  0x7fffe7b9ee18     (0x18007ee18) in terminate
#4  0x7fffe7b680a9     (0x1800480a9) in __C_specific_handler_noexcept
#5  0x7fffea3151de     (0x1800a51de) in __chkstk
#6  0x7fffea28e865     (0x18001e865) in RtlFindCharInUnicodeString
#7  0x7fffea2c4944     (0x180054944) in RtlRaiseException
#8  0x7fffe77cfabb     (0x18005fabb) in RaiseException
#9  0x7fffbb925266     (0x180005266) in _CxxThrowException
#10 0x7fffbb979621     (0x180039621) in void __cdecl std::_Xlength_error(char const * __ptr64)
#11 0x7fff6d437d2f     (0x180017d2f) in std::_Xlen_string() at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xstring:2340
#12 0x7fff6d437ef0     (0x180017ef0) in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char*, unsigned int) at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xstring:3220
#13 0x7fff6d440c56     (0x180020c56) in RakNet::RNS2_Windows_Linux_360::Send_Windows_Linux_360NoVDP(RakNet::RNS2_SendParameters*, char*, unsigned int) at D:\a\endstone\endstone\src\endstone_runtime\bedrock\deps\raknet\raknet_socket2.cpp:51
#14 0x7ff6d3b9ca1b     (0x14238ca1b) in  ??
#15 0x7ff6d3b8d555     (0x14237d555) in  ??
#16 0x7ff6d3b8cb9c     (0x14237cb9c) in  ??
#17 0x7ff6d3b92083     (0x142382083) in  ??
#18 0x7ff6d3b97593     (0x142387593) in  ??
#19 0x7fffe7b49332     (0x180029332) in _recalloc
#20 0x7fffe8f1257c     (0x18001257c) in BaseThreadInitThunk
#21 0x7fffea2caf27     (0x18005af27) in RtlUserThreadStart

**Comment by mandong1240** [comment]
But i found a way to avoid this bug.
I think that error occurs if the world name is in Korean, not English. Also, I hope you can support Korean in general.

**Comment by CoolLoong** [comment]
This may be related to the implementation of LevelDB. I don't think that the world file names need to support `non-ASCII` text

**Comment by mandong1240** [comment]
To do that, a similar phenomenon occurred in the folder name that was used when I installed EndStone.
