### ISSUE TITLE
[feature] Encrypted Resource Pack support

### ISSUE THREAD

**Issue by gamezaSRC** [EndstoneMC/endstone#63]
Many softwares supports this feature, I think endstone is the only one not supporting this at the moment. Since we don't have access to the packets in the api, I suggest to add this as a native feature of endstone. How does this work? Basicly be able to put our already encrypted packs and keys into a file or somewhere so when a player joins our server and is asked to download our resource packs it will send the RP packet info with our key so the client can use it to read the content.

Solution
A config file where we can put our encrypted packs UUID and Keys.
Another solution would be that endstone encrypt automatically all of our packs and store the keys to send them to the players when joining. Just like Allay software does.

This is really important for us the server owners, it's annoying that all of our packs and efforts get leaked, this will add an extra layer of security, at least now not everyone can leak our packs.

**Comment by wu-vincent** [comment]
Thank you for the suggestion! This is something we’ll definitely be adding shortly.

**Comment by wu-vincent** [comment]
Completed in https://github.com/EndstoneMC/endstone/commit/53c9dc16ecc7885ea5ff1eb1a9b0faf05b96b27d.
