### ISSUE TITLE
Endstone crashed on Linux

### ISSUE THREAD

**Issue by theamericanpsycho** [EndstoneMC/endstone#70]
My server crashed with instruction to report it as an issue in GitHub.

Attached Media:
![Endstone Crash Info Linux](https://github.com/user-attachments/assets/5c2d7730-ce9d-4b2f-8952-fe9127f64043)

I am not sure how it happened so can't really tell the steps to reproduce this. The only plugin installed is one that disables /me command, nothing else.

**Details (please complete the following information):**
 - OS: Linux
 - Endstone Version: v0.5.1

**Comment by wu-vincent** [comment]
Thank you for the report. After carefully inspecting the stack traces, it appears that BDS crashes when a player closes a container. The crash does not seem to be related to any code involving Endstone, so we believe this is a bug in BDS itself that we are unable to fix.
