### ISSUE TITLE
endstone_runtime.dll Access denied

### ISSUE THREAD

**Issue by TheNotEasy** [EndstoneMC/endstone#71]
**Describe the bug**
LoadLibrary failed to load endstone_runtime.dll with error 5

**To Reproduce**

1. Run `endstone`
2. Let it download bedrock server
3. And error

**Screenshots**
![Снимок экрана 2024-10-05 075614](https://github.com/user-attachments/assets/a1ff1a3d-8604-41cb-b6ac-bf86905072a0)
Translation: `...error 5: Access denied`

**Details:**
 - OS: Windows 11
 - Endstone Version: 0.5.4.1

**Additional context**
It's not problem with my filesystem, I gave it all permissions and even run it as administrator. And after closing message box, this happens in console: `OpenThread failed with error 18`. Issue where it's also happened: [#35](https://github.com/EndstoneMC/endstone/issues/35#issuecomment-2293376428).

**Comment by wu-vincent** [comment]
This looks like an issue on your end, and there’s not much we can do about it. I'd suggest trying a reboot to see if that helps.

**Comment by TheNotEasy** [comment]
The problem was that python was installed from the Microsoft store, reinstalled via the legacy installer and it worked! So issue, that I referenced, have this same issue, because he's also got microsoft store python version: [https://github.com/EndstoneMC/endstone/issues/35#issuecomment-2293803801](#35). It would be cool to add a warning about this in readme.
