### ISSUE TITLE
[feature] Add i18n API for Multilingual Support in Endstone

### ISSUE THREAD

**Issue by wu-vincent** [EndstoneMC/endstone#72]
**Is your feature request related to a problem? Please describe.**  
Currently, there’s no API in Endstone for handling multilingual messages.

**Describe the solution you'd like**  
1. Introduce Endstone's language files for translation.
2. Use BDS language file as a fallback if the key does not start with `endstone.`.
3. Translatable messages should be sent as-is to the client, allowing resource packs to handle their own translations, except for keys starting with `endstone.` which should be translated server-side.
4. Allow retrieval of translated messages using `server.getLanguage().translate(key, params)`.

**Describe alternatives you've considered**  
N/A

**Additional context**  
This API would follow a design similar to PocketMine-MP and Nukkit.

**Comment by smartcmd** [comment]
👀
