### ISSUE TITLE
[bug] When I create a boss bar and set it up through add_player, the boss bar is seen for 0.1 seconds and then disappears.

### ISSUE THREAD

**Issue by pgrd1** [EndstoneMC/endstone#76]
**Describe the bug**
When I create a boss bar and set it up through add_player, the boss bar is seen for 0.1 seconds and then disappears.

**To Reproduce**
When I make a boss bar through create_boss_bar and add_player, the boss bar is seen for a moment and then disappears

**Expected behavior**
I thought I'd see boss bar all the time

**Screenshots**

**Details (please complete the following information):**
 Windows 0.5.4.2.dev2

**Additional context**

**Comment by wu-vincent** [comment]
Thank you for reaching out. Could you provide a Minimal Working Example that can reproduce the issue?

**Comment by pgrd1** [comment]
It's the fastest code to see.    
@event_handler
    def on_block_interact(self, event: PlayerInteractEvent):  
        boss_test = self._plugin.server.create_boss_bar("DDDD",boss.BarColor.BLUE, boss.BarStyle.SOLID)
        boss_test.visible = True
        boss_test.add_player(event.player)

**Comment by wu-vincent** [comment]
I can't reproduce it myself. The boss bar appears to stay with the exact same code.
