### ISSUE TITLE
[feature] Add support for sending `AddActorPacket` to players

### ISSUE THREAD

**Issue by codemc1471** [EndstoneMC/endstone#77]
How to use the AddActor packet

I want to create a command to create and summon an Actor that is only visible to some users.

I found the AddActor packet but I'm not sure how to use it.

**Comment by wu-vincent** [comment]
Thank you for your question. At present, the only custom packet type supported by our network API is the `SpawnParticleEffectPacket`. However, to create an Actor that is visible only to specific players, the `AddActorPacket` will indeed be the appropriate choice. I am planning to implement this functionality soon.

**Comment by codemc1471** [comment]
thanks
