### ISSUE TITLE
[bug] Can't get player scoreboard value correctly

### ISSUE THREAD

**Issue by Monarchdos** [EndstoneMC/endstone#78]
**Describe the bug**
Can't get player scoreboard value correctly!

**To Reproduce**
board = args[0].strip('"')
objective = self.server.scoreboard.get_objective(board)
score = objective.get_score(sender.name)
sender.send_message(f"{score.value}")
 self.logger.info(f"Score: player={sender.name}, objective={objective.name}, value={score.value}, is_set={score.is_score_set}")

**Screenshots**
![2024-10-14_14-09-33](https://github.com/user-attachments/assets/07f1ccf1-40a2-4356-8da3-c1ad4cc8ae32)

**Details (please complete the following information):**
 - Endstone Version: [e.g. v0.5.4.1]

**Comment by pgrd1** [comment]
Try using sender instead of sender.name
