### ISSUE TITLE
Create a Discord server to communicate with the endstone users

### ISSUE THREAD

**Issue by Mih4n** [EndstoneMC/endstone#8]
And leave it in github readme.

**Comment by Hahaa13** [comment]
Wait :V

**Comment by wu-vincent** [comment]
Thank you for your suggestion and your interest in the Endstone project! We plan to set up the Discord server closer to the project's beta testing phase. We will update the project's README with the Discord server details as soon as it's live!

**Comment by Hahaa13** [comment]
Waittttttt :))

**Comment by smartcmd** [comment]
+1

**Comment by Adrian8115** [comment]
+2

**Comment by Spicearth** [comment]
+1

**Comment by Hahaa13** [comment]
True

**Comment by Hahaa13** [comment]
> We really need endstone to become a large community, keep it up bro!
> This will be the first time ever having python scripting for minecraft bedrock

True
Although maybe my expectations are a bit far, I really want EndStone to succeed because I like minecraft bedrock more than java because it's much better optimized and what bedrock lacks is a server with java-like plugins.

**Comment by Mih4n** [comment]
Hooray and where is champagne

**Comment by wu-vincent** [comment]
Great news! The invite link to our Discord server is now added to the README.md. I'm closing this issue now, but the conversation is just getting started over on Discord. Looking forward to meeting you all there.

**Comment by Hahaa13** [comment]
Holyyyyyy NICE

**Comment by Mih4n** [comment]
Hooray but where is the link. I'm blind a bit

**Comment by nicholass003** [comment]
> Hooray but where is the link. I'm blind a bit

click discord icon at README

**Comment by Mih4n** [comment]
Thanks
