### ISSUE TITLE
it's not working in arm64 debian

### ISSUE THREAD

**Issue by Xwens-e** [EndstoneMC/endstone#86]
Building wheel for endstone (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for endstone (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      /tmp/pip-build-env-2m9eyngx/normal/lib/python3.9/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
        warnings.warn("git archive did not support describe output")
      /tmp/pip-build-env-2m9eyngx/normal/lib/python3.9/site-packages/setuptools_scm/git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
        warnings.warn("unprocessed git archival found (no export subst applied)")
      *** scikit-build-core 0.10.7 using CMake 3.18.4 (wheel)
      *** Configuring CMake...
      CMake Error: Could not create named generator  Ninja

      Generators
        Unix Makefiles               = Generates standard UNIX makefiles.
        Green Hills MULTI            = Generates Green Hills MULTI files
                                       (experimental, work-in-progress).
      * Ninja                        = Generates build.ninja files.
        Ninja Multi-Config           = Generates build-<Config>.ninja files.
        Watcom WMake                 = Generates Watcom WMake makefiles.
        CodeBlocks - Ninja           = Generates CodeBlocks project files.
        CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
        CodeLite - Ninja             = Generates CodeLite project files.
        CodeLite - Unix Makefiles    = Generates CodeLite project files.
        Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
        Sublime Text 2 - Unix Makefiles
                                     = Generates Sublime Text 2 project files.
        Kate - Ninja                 = Generates Kate project files.
        Kate - Unix Makefiles        = Generates Kate project files.
        Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
        Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for endstone
Failed to build endstone
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (endstone)
./autoinstall.sh:行87: endstone：未找到命令

**Comment by wu-vincent** [comment]
Arm64 is not supported because there is no arm64 build for BDS.
