### ISSUE TITLE
[bug] Can't start the endstone, undefined symbol: PyProperty_Type

### ISSUE THREAD

**Issue by Monarchdos** [EndstoneMC/endstone#94]
**Describe the bug**
Can't start under Ubuntu after building the latest version of the source code, Windows works fine.
I've tried using GitHub action and compiling locally, both with the same result.

**Screenshots**
![image](https://github.com/user-attachments/assets/a73d2403-23c2-46d1-b843-d20fc86ebbab)

**Details (please complete the following information):**
 - OS: Linux ubuntu 22.04
 - Endstone Version: endstone-0.5.6.dev41

**Additional context**
symbol lookup error: /usr/local/lib/python3.10/dist-packages/endstone/_internal/libendstone_runtime.so: undefined symbol: PyProperty_Type

**Comment by smartcmd** [comment]
What is your python version?

**Comment by Monarchdos** [comment]
Python 3.9,3.10,3.12 tried it all.

**Comment by FTS427** [comment]
try cleaning your env, reinstalling python and endstone

**Comment by Monarchdos** [comment]
> try cleaning your env, reinstalling python and endstone

Yes I tried that, originally I only had python 3.9 and 3.10, I newly installed python 3.12 and installed python 3.12 version endstone,still the same!

**Comment by FTS427** [comment]
rm /usr/local/lib/python3.10/dist-packages/endstone/ -rf
then update pip and install endstone again?

**Comment by Monarchdos** [comment]
> rm /usr/local/lib/python3.10/dist-packages/endstone/ -rf
> then update pip and install endstone again?

Yes I have done the install several times and uninstall will remove the directory and pip is up to date.

**Comment by FTS427** [comment]
🥲

**Comment by wu-vincent** [comment]
Thank you for reporting this! I can confirm that this is indeed a bug introduced by recent changes in the build pipeline. I will provide a fix soon.

**Comment by wu-vincent** [comment]
Fixed in the latest commits.
