### ISSUE TITLE
[feature] hooking

### ISSUE THREAD

**Issue by yurasulima** [EndstoneMC/endstone#95]
**Is your feature request related to a problem? Please describe.**
--

**Describe the solution you'd like**
add the ability and guide to use hooks, this will help implement some features while you are developing them in endstone

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by wu-vincent** [comment]
Hooking support is not a goal of this project. We aim to provide a high-level API to shield users from dealing with low-level hooks. Hooking is inherently risky, non-portable, and can easily break with version updates. It requires significant reverse-engineering expertise to do it correctly.

That said, we do provide a C++ API, so you are free to use any off-the-shelf hooking library in C or C++ to meet your specific needs.
