### ISSUE TITLE
second name for player

### ISSUE THREAD

**Issue by Mih4n** [EndstoneMC/endstone#96]
player in scripting api have two name one is immutable name and other is name tag. Would be nice to see this feature in endstone

**Comment by wu-vincent** [comment]
Completed in https://github.com/EndstoneMC/endstone/commit/d3979e1b4f143c634277380743b4683eb6e32889.

For API reference, see [Actor.name_tag](https://endstone.dev/latest/reference/python/actor/#endstone.actor.Actor.name_tag).
