### ISSUE TITLE
[feature] Issue with Loading Custom Plugins in Endstone due to Plugin Loading Mechanism 

### ISSUE THREAD

**Issue by engsr6982** [EndstoneMC/endstone#98]
**Is your feature request related to a problem? Please describe.**

I'm trying to write other language engines for Endstone (although the Python functionality provided by Endstone is stronger). However, the plugin loading mechanism of Endstone prevents me from loading plugins of custom types, such as.lua ones.
Because I need to wait for Endstone to load my engine DLL before I can register the loader with Endstone. But by this time, Endstone has already completed the loading and will no longer call the newly added loader.
I've tried to manually call the "loadPlugins" function, but Endstone doesn't check whether the plugins have been loaded, which will lead to an infinite loop. Besides, the members of Endstone_plugin_manager are private, and I can't register them manually either.
**Describe the solution you'd like**

Could you add a couple of overloads to EndStonePluginManager::loadPlugins(const std::string &directory), for example: 

`EndStonePluginManager::loadPlugins(const std::string &directory, string const& loader_type)`

or

`EndStonePluginManager::loadPlugins(const std::string &directory, PluginLoader& loader)`

**Comment by wu-vincent** [comment]
Thanks for the issue! This is indeed something in the current design that needs improvement.

I’m currently refactoring the plugin loading mechanism to address this. I’ve added a new function, `PluginManager::loadPlugin(std::string file)`, which allows loading a plugin directly from a single file instead of a directory. I’ve also introduced an overload for `PluginManager::loadPlugins(std::vector<std::string>)` that accepts a list of file paths instead of just a directory.

These changes should enable you to load your custom plugins without encountering infinite loops. Most of the refactoring work mentioned above is completed in [this commit](https://github.com/EndstoneMC/endstone/commit/0b4cc7c93d5c41feb4732a0635c44875c3b926f3), but I still need to perform more testing.

**Comment by wu-vincent** [comment]
Close as it's completed now. The new API will be available in the upcoming release v0.5.6.

**Comment by engsr6982** [comment]
> Thanks for the issue! This is indeed something in the current design that needs improvement.
> 
> I’m currently refactoring the plugin loading mechanism to address this. I’ve added a new function, `PluginManager::loadPlugin(std::string file)`, which allows loading a plugin directly from a single file instead of a directory. I’ve also introduced an overload for `PluginManager::loadPlugins(std::vector<std::string>)` that accepts a list of file paths instead of just a directory.
> 
> These changes should enable you to load your custom plugins without encountering infinite loops. Most of the refactoring work mentioned above is completed in [this commit](https://github.com/EndstoneMC/endstone/commit/2c9e13e3f8b4d83a5cce412f52b269da58b57b64), but I still need to perform more testing.


I tested these two new overloaded functions and found that custom plugins still cannot be properly registered with Endstone.

Here's my registration process:
When Endstone loads my DLL, I register a custom Loader in the onLoad function. Then I search for the file paths I expect to load in the plugins directory and pass them to the `PluginManager::loadPlugins(std::vector<std::string> files)` function.

However, `PluginManager::loadPlugins` calls `PluginManager::loadPlugin(file)`, which iterates through each Loader trying to find one that can load this file. The problem occurs here - this function doesn't perform any checks and doesn't call `getPluginFileFilters()` for filtering. Instead, it directly passes the file path to both Cpp and Py Loaders, causing exceptions and crashes.

**Comment by engsr6982** [comment]
> > Thanks for the issue! This is indeed something in the current design that needs improvement.
> > I’m currently refactoring the plugin loading mechanism to address this. I’ve added a new function, `PluginManager::loadPlugin(std::string file)`, which allows loading a plugin directly from a single file instead of a directory. I’ve also introduced an overload for `PluginManager::loadPlugins(std::vector<std::string>)` that accepts a list of file paths instead of just a directory.
> > These changes should enable you to load your custom plugins without encountering infinite loops. Most of the refactoring work mentioned above is completed in [this commit](https://github.com/EndstoneMC/endstone/commit/2c9e13e3f8b4d83a5cce412f52b269da58b57b64), but I still need to perform more testing.
> 
> I tested these two new overloaded functions and found that custom plugins still cannot be properly registered with Endstone.
> 
> Here's my registration process: When Endstone loads my DLL, I register a custom Loader in the onLoad function. Then I search for the file paths I expect to load in the plugins directory and pass them to the `PluginManager::loadPlugins(std::vector<std::string> files)` function.
> 
> However, `PluginManager::loadPlugins` calls `PluginManager::loadPlugin(file)`, which iterates through each Loader trying to find one that can load this file. The problem occurs here - this function doesn't perform any checks and doesn't call `getPluginFileFilters()` for filtering. Instead, it directly passes the file path to both Cpp and Py Loaders, causing exceptions and crashes.


I forked the project and fixed the problem. But I found a more serious problem, if any plugin registers (modifies) the Vector that holds the Loader during onLoad, it will cause the iterator to fail and trigger a crash.

fork: https://github.com/engsr6982/endstone/commit/dd2d97f9f3cd8ee98c5760eca098edb76df322bb
Iterator failure location: https://github.com/EndstoneMC/endstone/blob/8dd9acfc5c114edf5ee1e14d050e02863231bb24/src/endstone_core/plugin/plugin_manager.cpp

**Comment by wu-vincent** [comment]
To address cases where the vector may be modified during iteration, I’ve made an additional commit to fix the issue. You can check it here: https://github.com/EndstoneMC/endstone/commit/6ed7faf87c6febe70f007a51f3012f90db376513

Can you verify if this resolves the problem?

**Comment by engsr6982** [comment]
> To address cases where the vector may be modified during iteration, I’ve made an additional commit to fix the issue. You can check it here: [6ed7faf](https://github.com/EndstoneMC/endstone/commit/6ed7faf87c6febe70f007a51f3012f90db376513)
> 
> Can you verify if this resolves the problem?

Thanks, it's been verified and the code is running fine so far!
